language: php

php:
  - 7.0

env:
  - ENCRYPTION_KEY=48ca7483a0bb52c4d26e9ced9b436552a27ff44e821203104f571bbaff5a394d

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o

script: vendor/bin/phpunit --verbose

notifications:
  email:
    - dbyoung2@gmail.com

sudo: false

matrix:
  fast_finish: true