language: php

php:
  - 7.0
  - 7.1

env:
  - ENV_NAME=testing
  - ENCRYPTION_KEY=48ca7483a0bb52c4d26e9ced9b436552a27ff44e821203104f571bbaff5a394d

before_install:
  - composer self-update

install:
  - composer install
  - composer dump-autoload -o

script: vendor/bin/phpunit --verbose

notifications:
  email:
    - dbyoung2@gmail.com

sudo: false

matrix:
  allow_failures:
    - php: 7.1
  fast_finish: true